<a href="https://colab.research.google.com/github/NiloufarAsghari/PyTorch-Tutorial/blob/main/DeepLearningWithPytorch3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

This Link can help you alot\
https://www.youtube.com/watch?v=IHZwWFHWa-w

Gradient ---> Model Optimization


In [1]:
#Autograd
#Gradient Computation

import torch

In [4]:
x=torch.rand(2,requires_grad=True) #PyTorch will create Computational Graph ---> When Operation
print(x)

tensor([0.6061, 0.4242], requires_grad=True)


In [10]:
#Let's Try Operation on X
y=x+2  #GradFunction---> AddBackward
print(y)

#More operation
z=y*y*2  #Func ---> Multiple
print(z)

#Apply Mean Operation
z=z.mean()
print(z)

#calculate the gradient
z.backward()  # dz/dx

#where the gradients stored
print(x.grad)

tensor([2.6061, 2.4242], grad_fn=<AddBackward0>)
tensor([13.5834, 11.7537], grad_fn=<MulBackward0>)
tensor(12.6686, grad_fn=<MeanBackward0>)
tensor([5.2122, 4.8485])


In [14]:
#if we don't specify requires_grad=True

x1=torch.rand(2)  #by default requires_grad is False
print(x1)
y1=x1*2
z1=y1*y1*2
z1=z1.mean()
z1.backward()  #Obviously we get the error !
#print(x1.grad)

tensor([0.6111, 0.2769])


RuntimeError: ignored

In [17]:
x2=torch.rand(2, requires_grad=True)  
print(x2)
y2=x2*2
z2=y2*y2*2
#z2=z2.mean()   #Operation create Scalar value

#create vector of same size as x2

v=torch.tensor([0.002,0.02],dtype=torch.float32)
#pass vector V to backward function

z2.backward(v) #now although we commented z.mean() we can run the code without error 

print(x2.grad)

tensor([0.1345, 0.2964], requires_grad=True)
tensor([0.0043, 0.0949])


In [23]:
#Prevent From Tracking Gradients

x3= torch.rand(2, requires_grad=True)
print(x3)
#option 1  ---> requires_grad_(Flase)
x3=x3.requires_grad_(False)
print(x3)


#option 2  ---> x.detach() create new tensor that doesn't require new gradient
#create new tensor with the same values but it doesn't require new gradient
y3=x3.detach()
print(y3)



#option 3  ---> whit torch.no_grad() 
with torch.no_grad():
  z3=x3+2
  print(z3)




tensor([0.0443, 0.8087], requires_grad=True)
tensor([0.0443, 0.8087])
tensor([0.0443, 0.8087])
tensor([2.0443, 2.8087])


Before we want to do the next operation or the next iteration in our optimization steps, we

**Must empty our gradient**

grad.zero_()

In [27]:
#ex

weights=torch.ones(2,requires_grad=True)


#training loop
for epoch in range(3):  #we will see for each epoch(iteration) backward will accumulate the values and write them in grad wich is not right
  #a simple operation
  model_out=(weights*2).sum()
  model_out.backward()
  #Print Gradients
  print(weights.grad)

  #to prevent accumulating we must empty the gradients  ---> Uncomment the code below
 # weights.grad.zero_()

tensor([2., 2.])
tensor([4., 4.])
tensor([6., 6.])


In [ ]:
#work with optimizer use torch optimization package
weights=torch.ones(3,requires_grad=True)

optimizer=torch.optim.SGD(weights, lr=0.01)
#with that optimizer, do optimization step
optimizer.step()
#before we go to our nexr optimization step we must empty our gradient
optimizer.zero_grad()