<a href="https://colab.research.google.com/github/NiloufarAsghari/Pytorch-Tutorial/blob/main/DeepLearningWithPytorch2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
#make an empty tensor


#1D array with 2 values
x=torch.empty(2)

#2D Arrays
y=torch.empty(2,3)


#Create Tensor with Random Value
z=torch.rand(2,2)

#Like Numpy Tensor With Zero values
R=torch.zeros(2,2)

#Like Numpy Tensor With One values
q=torch.ones(2,2)


#Change the dtype Parameter ---> Default=torch.float32

y=torch.empty(2,3,dtype=torch.int)

#Create Tensor using Array

xx=torch.tensor([1.2,3.5])

In [ ]:
print(x)
print(y)
print(z)
print(R)
print(q)
print(x.dtype)
print(y.dtype)
print(x.size())
print(xx)

tensor([1.1403e-35, 0.0000e+00])
tensor([[91394176,        0,        0],
        [       0,        0,        0]], dtype=torch.int32)
tensor([[0.3718, 0.2406],
        [0.6130, 0.8531]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])
torch.float32
torch.int32
torch.Size([2])
tensor([1.2000, 3.5000])


In [ ]:
#Sum
x=torch.rand(2,2)
y=torch.rand(2,2)
print(x)
print(y)


#1st Way to SUM
#z=x+y 
#OR
#z=torch.add(x,y)
#print(z)

#2nd Way to SUM
y.add_(x)
print(y)


#Sub
xx=torch.rand(2,2)
yy=torch.rand(2,2)
zz=torch.sub(xx,yy)
#OR
#y.sub_(x)
#print(y)



#Multiple
x2=torch.rand(2,2)
y2=torch.rand(2,2)
z2=torch.mul(x2,y2)

#Divid
x3=torch.rand(2,2)
y3=torch.rand(2,2)
z3=torch.div(x3,y3)





print(zz)
print(z2)
print(z3)


tensor([[0.0667, 0.3340],
        [0.7654, 0.4920]])
tensor([[0.2987, 0.2480],
        [0.3114, 0.6345]])
tensor([[0.3655, 0.5820],
        [1.0768, 1.1265]])
tensor([[-0.4849, -0.5917],
        [-0.1589, -0.1285]])
tensor([[0.1259, 0.3636],
        [0.0222, 0.4867]])
tensor([[0.6242, 4.5269],
        [1.8357, 2.7360]])


In [ ]:
x=torch.rand(5,3)
print(x) #Whole Tensor
print(x[:,0])   #ALL rows but Column 0
print(x[1,:])   #row 1 but ALL columns

print(x[1,1].item())   #Actual Value

tensor([[0.9174, 0.5620, 0.7909],
        [0.4529, 0.2490, 0.7532],
        [0.4202, 0.8289, 0.8184],
        [0.0688, 0.0137, 0.2581],
        [0.0800, 0.4873, 0.9666]])
tensor([0.9174, 0.4529, 0.4202, 0.0688, 0.0800])
tensor([0.4529, 0.2490, 0.7532])
0.2489910125732422


In [ ]:
#Reshape/resize into 1D array

x=torch.rand(4,4)
print(x)
#y=x.view(16)
#print(y)


#OR 
y=x.view(-1,8)
print(y.size())

tensor([[0.3134, 0.2684, 0.2668, 0.2503],
        [0.1488, 0.6928, 0.6821, 0.6400],
        [0.0850, 0.1529, 0.3559, 0.0163],
        [0.6862, 0.2307, 0.5651, 0.5860]])
torch.Size([2, 8])


In [ ]:
#Converting From Numpy to Torch or <--->

import numpy as np

a=torch.ones(5)
print(a)
b=a.numpy()
print(type(b))

a.add_(1)
print(a)
print(b) #Cause they both point to the same memory location



# <---->
a2=np.ones(5)
print(a2)
print(type(a2))
b2=torch.from_numpy(a2)
print(b2)

a2 +=1
print(a2)
print(b2)

tensor([1., 1., 1., 1., 1.])
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [ ]:
#if we have a variable needs to be optimized later
x=torch.ones(5, requires_grad=True)  # Needs to calculate gradient for this tensor later in optimization steps
print(x)


tensor([1., 1., 1., 1., 1.], requires_grad=True)
